name: Test deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - "web/games/**"
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: web/games/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: web/games

      - name: Lint website
        run: yarn lint
        working-directory: web/games

      - name: Test build website
        run: yarn build
        working-directory: web/games
